### ISSUE TITLE
ReferenceError: EJSON is not defined at Object.verifyCaptcha (packages/altapp_recaptcha.js:63:9)

### ISSUE THREAD

**Issue by KaitaniLabs** [Altapp/Meteor-reCAPTCHA#13]
Meteor 1.6.0.1

**Comment by CongDo0820** [comment]
have u had it fixed ???

**Comment by tomasz-nolberczak** [comment]
@KaitaniLabs @CongFIMO 

It looks like you need to simply add `ejson` package to your application, by typing in your terminal:

```bash
meteor add ejson
```

For me a problem no longer occurs. Everything is working well with Meteor@1.6.1.

I have also created a [fork](https://github.com/tomasz-nolberczak/Meteor-reCAPTCHA) of this package, you can install it from the GitHub as local package. In that fork I have added `ejson` to dependencies. 

@manybothans please think about merging my changes to the main repo. Thanks! :clap:

**Comment by KaitaniLabs** [comment]
@tomasz-nolberczak thanks for the heads up. I assumed it was included by default.

**Comment by tomasz-nolberczak** [comment]
@KaitaniLabs please close this issue. It looks like it is working with `ejson` lib.
