### ISSUE TITLE
not working on mobile devices

### ISSUE THREAD

**Issue by garrilla** [Altapp/Meteor-reCAPTCHA#2]
well, it's not working on android kitkat with chrome 39.0.2171.59 on Galaxys S4 on android lollipop also chrome  39.0.2171.59 and firefox 33.1 on Nexus 10.

it just places text `loading...`

and waits forever

Is this the package or something more fundamental to recaptcha ?

**Comment by prachi708** [comment]
Hi, I am also facing the same problem. Can you please more elaborate how you resolved it. 
For my API key registered url's are: 
1) my website address
2) localhost
What more I have to add here?
