### ISSUE TITLE
Meteor-reCAPTCHA v2.0

### ISSUE THREAD

**Issue by shaferain** [Altapp/Meteor-reCAPTCHA#3]
Hello there,

Perhaps you've noticed the changes made to Google recaptcha as they call it 'No Captcha reCaptcha' - just an easier way for users to verify themselves by a simple clicking. I've installed your Meteor-reCAPTCHA package and found it very convenient to use, and then finally managed to modify the script to implement 'No Captcha reCaptcha'. Are you interested in updating your package? I can just propose changes in your script here so you can approve easily. Let me know how you think, and thank you for making this package available in the first place!

**Comment by tobiaghiraldini** [comment]
Hello!
I am also using your package, so thank you for your work!
I was just doing the same thing as shaferain here, so I am really interested in contributing and getting shaferain work in it as well...

**Comment by manybothans** [comment]
Hey sorry for the extremely slow reply. Package has been updated to new style with `altapp:recaptcha@2.0.0`.
